Theres an error Console Error
Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

src/components/ui/scroll-area.tsx (12:3) @ _c

  10 |   React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>
  11 | >(({ className, children, ...props }, ref) => (
> 12 |   <ScrollAreaPrimitive.Root
     |   ^
  13 |     ref={ref}
  14 |     className={cn("relative overflow-hidden", className)}
  15 |     {...props}
Call Stack
56

Show 52 ignore-listed frame(s)
Array.map
<anonymous> (0:0)
div
<anonymous> (0:0)
_c
src/components/ui/scroll-area.tsx (12:3)
GamePage
src/app/game/[mapId]/page.tsx (724:21)

Unhandled Runtime Error

Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

src/components/ui/scroll-area.tsx (12:3) @ _c

  10 |   React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>
  11 | >(({ className, children, ...props }, ref) => (
> 12 |   <ScrollAreaPrimitive.Root
     |   ^
  13 |     ref={ref}
  14 |     className={cn("relative overflow-hidden", className)}
  15 |     {...props}
Call Stack
56

Show 52 ignore-listed frame(s)
Array.map
<anonymous> (0:0)

Unhandled Runtime Error

Error: Cannot read properties of null (reading 'parentElement')

src/app/game/[mapId]/page.tsx (391:36) @ GamePage.useEffect.initJoystick

  389 |                 const nipplejs = (await import('nipplejs')).default;
  390 |
> 391 |                 manager = nipplejs.create({
      |                                    ^
  392 |                     zone: joystickZoneRef.current, // The DOM element for the joystick area
  393 |                     mode: 'dynamic', // Allows joystick to appear where finger touches
  394 |                     position: { left: '50%', top: '50%' }, // Centered in the zone initially
Call Stack
5

Show 4 ignore-listed frame(s)
GamePage.useEffect.initJoystick
src/app/game/[mapId]/page.tsx (391:36)

Unhandled Runtime Error

Error: Failed to execute 'getProgramParameter' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.

Call Stack
14

Show 14 ignore-listed frame(s)

Unhandled Runtime Error

Error: Framebuffer status: Incomplete Attachment

Call Stack
10

Show 10 ignore-listed frame(s)